In [29]:
import pandas as pd 
import os
import datetime as dt

In [3]:
# File to Load (Remember to Change These)
file_to_load1 = "Data/User1.csv"
file_to_load2 = "Data/User2.csv"
file_to_load3 = "Data/User3.csv"
file_to_load4 = "Data/User4.csv"
file_to_load5 = "Data/User5.csv"
file_to_load6 = "Data/User6.csv"
file_to_load7 = "Data/User7.csv"
file_to_load8 = "Data/User8.csv"
file_to_load9 = "Data/User9.csv"
file_to_load10 = "Data/User10.csv"
file_to_load11 = "Data/User11.csv"
file_to_load12 = "Data/User12.csv"
file_to_load13 = "Data/User13.csv"
file_to_load14 = "Data/User14.csv"
file_to_load15 = "Data/User15.csv"
file_to_load16 = "Data/User16.csv"
file_to_load17 = "Data/User17.csv"
file_to_load18 = "Data/User18.csv"
file_to_load19 = "Data/User19.csv"
file_to_load20 = "Data/User20.csv"
file_to_load21 = "Data/User21.csv"
file_to_load22 = "Data/User22.csv"
file_to_load23 = "Data/User23.csv"
file_to_load24 = "Data/User24.csv"
file_to_load25 = "Data/User25.csv"
file_to_load26 = "Data/User26.csv"
file_to_load27 = "Data/User27.csv"
file_to_load28 = "Data/User28.csv"
file_to_load29 = "Data/User29.csv"


# Read Purchasing File and store into Pandas data frame
user1_data = pd.read_csv(file_to_load1)
user2_data = pd.read_csv(file_to_load2)
user3_data = pd.read_csv(file_to_load3)
user4_data = pd.read_csv(file_to_load4)
user5_data = pd.read_csv(file_to_load5)
user6_data = pd.read_csv(file_to_load6)
user7_data = pd.read_csv(file_to_load7)
user8_data = pd.read_csv(file_to_load8)
user9_data = pd.read_csv(file_to_load9)
user10_data = pd.read_csv(file_to_load10)
user11_data = pd.read_csv(file_to_load11)
user12_data = pd.read_csv(file_to_load12)
user13_data = pd.read_csv(file_to_load13)
user14_data = pd.read_csv(file_to_load14)
user15_data = pd.read_csv(file_to_load15)
user16_data = pd.read_csv(file_to_load16)
user17_data = pd.read_csv(file_to_load17)
user18_data = pd.read_csv(file_to_load18)
user19_data = pd.read_csv(file_to_load19)
user20_data = pd.read_csv(file_to_load20)
user21_data = pd.read_csv(file_to_load21)
user22_data = pd.read_csv(file_to_load22)
user23_data = pd.read_csv(file_to_load23)
user24_data = pd.read_csv(file_to_load24)
user25_data = pd.read_csv(file_to_load25)
user26_data = pd.read_csv(file_to_load26)
user27_data = pd.read_csv(file_to_load27)
user28_data = pd.read_csv(file_to_load28)
user29_data = pd.read_csv(file_to_load29)

In [4]:
user1 = user1_data.assign(Group= '1')
user2 = user2_data.assign(Group= '2')
user3 = user3_data.assign(Group= '3')
user4 = user4_data.assign(Group= '4')
user5 = user5_data.assign(Group= '5')
user6 = user6_data.assign(Group= '6')
user7 = user7_data.assign(Group= '7')
user8 = user8_data.assign(Group= '8')
user9 = user9_data.assign(Group= '9')
user10 = user10_data.assign(Group= '10')
user11 = user11_data.assign(Group= '11')
user12 = user12_data.assign(Group= '12')
user13 = user13_data.assign(Group= '13')
user14 = user14_data.assign(Group= '14')
user15 = user15_data.assign(Group= '15')
user16 = user16_data.assign(Group= '16')
user17 = user17_data.assign(Group= '17')
user18 = user18_data.assign(Group= '18')
user19 = user19_data.assign(Group= '19')
user20 = user20_data.assign(Group= '20')
user21 = user21_data.assign(Group= '21')
user22 = user22_data.assign(Group= '22')
user23 = user23_data.assign(Group= '23')
user24 = user24_data.assign(Group= '24')
user25 = user25_data.assign(Group= '25')
user26 = user26_data.assign(Group= '26')
user27 = user27_data.assign(Group= '27')
user28 = user28_data.assign(Group= '28')
user29 = user29_data.assign(Group= '29')

In [5]:
combined = pd.concat([user1, user2, user3, user4, user5, user6, user7, user8, user9, user10, user11, user12, user13, user14, user15, user16, user17, user18, user19, user20, user21, user22, user23, user24, user25, user26, user27, user28, user29])

In [117]:
combined.head(45)

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code,Group
0,12/13/2020 at 1:26:56 am EST,Crewmate,Win,3,No,Yes,-,07m 04s,No,2.0,-,++,NA / WYMSBF,1
1,12/13/2020 at 1:17:42 am EST,Crewmate,Loss,7,Yes,No,-,16m 21s,No,1.0,09m 48s,--,NA / WYMSBF,1
2,12/13/2020 at 12:57:47 am EST,Crewmate,Win,3,No,No,-,11m 33s,No,0.0,-,++,NA / WYMSBF,1
3,12/13/2020 at 12:41:55 am EST,Imposter,Win,-,-,-,2,08m 05s,No,NaN,-,+++,Europe / QIRTNF,1
4,12/13/2020 at 12:30:37 am EST,Crewmate,Loss,4,No,No,-,05m 10s,No,0.0,-,---,Europe / QIRTNF,1
5,12/13/2020 at 12:24:20 am EST,Crewmate,Loss,7,Yes,Yes,-,16m 22s,No,0.0,12m 16s,--,Europe / QIRTNF,1
6,12/13/2020 at 12:00:39 am EST,Crewmate,Loss,8,Yes,Yes,-,21m 41s,No,1.0,18m 38s,--,Europe / MTKPVF,1
7,12/11/2020 at 4:15:08 pm EST,Crewmate,Win,8,Yes,No,-,18m 43s,Yes,0.0,07m 48s,++,Europe / BFRJCF,1
8,12/11/2020 at 3:49:33 pm EST,Crewmate,Win,7,Yes,Yes,-,13m 15s,No,0.0,13m 15s,++,Europe / BFRJCF,1
9,12/11/2020 at 3:30:36 pm EST,Crewmate,Loss,7,Yes,Yes,-,12m 43s,No,0.0,12m 43s,--,Europe / BFRJCF,1
10,12/11/2020 at 3:10:58 pm EST,Crewmate,Win,4,No,Yes,-,11m 00s,No,0.0,-,++,Europe / BFRJCF,1
11,12/11/2020 at 2:53:28 pm EST,Crewmate,Win,7,Yes,No,-,17m 43s,No,0.0,11m 59s,++,Europe / BFRJCF,1
12,12/11/2020 at 2:20:38 pm EST,Crewmate,Loss,6,No,Yes,-,13m 46s,No,0.0,-,---,Europe / ONSJWQ,1
13,12/11/2020 at 2:04:26 pm EST,Imposter,Loss,-,-,-,3,15m 52s,Yes,NaN,-,-,Europe / ONSJWQ,1
14,12/11/2020 at 1:46:30 pm EST,Crewmate,Win,7,Yes,Yes,-,18m 54s,No,1.0,11m 09s,++,Europe / ONSJWQ,1
15,12/11/2020 at 2:09:32 am EST,Crewmate,Loss,7,Yes,Yes,-,08m 00s,No,0.0,01m 41s,--,NA / EYNONF,1
16,12/11/2020 at 2:00:26 am EST,Crewmate,Win,7,Yes,Yes,-,18m 06s,No,0.0,09m 34s,++,NA / EYNONF,1
17,12/11/2020 at 1:26:11 am EST,Crewmate,Win,7,Yes,Yes,-,12m 58s,No,1.0,09m 03s,++,NA / EYNONF,1
18,12/11/2020 at 1:03:05 am EST,Crewmate,Win,7,Yes,Yes,-,14m 57s,No,0.0,14m 50s,++,NA / EYNONF,1
19,12/11/2020 at 12:45:34 am EST,Crewmate,Loss,7,Yes,Yes,-,11m 03s,No,0.0,10m 34s,--,NA / EYNONF,1
20,12/11/2020 at 12:29:51 am EST,Crewmate,Loss,2,No,Yes,-,14m 43s,No,0.0,-,---,NA / EYNONF,1
21,12/11/2020 at 12:09:02 am EST,Crewmate,Loss,3,No,Yes,-,08m 34s,No,1.0,-,---,NA / EYNONF,1
22,12/10/2020 at 11:59:38 pm EST,Crewmate,Loss,8,Yes,No,-,05m 32s,No,0.0,05m 32s,--,NA / EYNONF,1
23,12/10/2020 at 11:50:32 pm EST,Crewmate,Win,8,Yes,Yes,-,16m 44s,No,0.0,14m 45s,++,NA / EYNONF,1
24,12/10/2020 at 11:31:47 pm EST,Crewmate,Loss,8,Yes,Yes,-,09m 11s,No,1.0,08m 29s,--,NA / EYNONF,1
25,12/10/2020 at 11:21:16 pm EST,Crewmate,Loss,8,Yes,Yes,-,14m 50s,No,0.0,05m 56s,--,NA / EYNONF,1
26,12/10/2020 at 11:03:55 pm EST,Crewmate,Loss,8,Yes,Yes,-,17m 49s,No,0.0,17m 12s,--,NA / EYNONF,1
27,12/10/2020 at 10:41:43 pm EST,Imposter,Loss,-,-,-,2,18m 01s,No,NaN,-,-,NA / EYNONF,1
28,12/10/2020 at 10:22:09 pm EST,Crewmate,Win,8,Yes,Yes,-,11m 50s,No,1.0,06m 00s,++,NA / EYNONF,1
29,12/10/2020 at 12:44:53 am EST,Crewmate,Win,5,Yes,No,-,09m 26s,No,2.0,08m 16s,++,Europe / KTQRWQ,1
30,12/10/2020 at 12:34:34 am EST,Crewmate,Win,1,No,No,-,03m 08s,No,1.0,-,NaN,Europe / KTQRWQ,1
31,12/10/2020 at 12:30:51 am EST,Imposter,Loss,-,-,-,1,02m 35s,Yes,NaN,-,NaN,Europe / KTQRWQ,1
32,12/10/2020 at 12:26:19 am EST,Crewmate,Win,1,No,No,-,02m 27s,No,0.0,-,NaN,Europe / KTQRWQ,1
33,12/10/2020 at 12:22:45 am EST,Crewmate,Win,3,No,No,-,04m 53s,No,1.0,-,NaN,Europe / KTQRWQ,1
34,12/10/2020 at 12:10:31 am EST,Crewmate,Win,1,No,Yes,-,05m 24s,No,0.0,-,++,Europe / BNDUNF,1
35,12/09/2020 at 11:52:22 pm EST,Imposter,Loss,-,-,-,2,19m 39s,No,NaN,-,-,Europe / BNDUNF,1
36,12/09/2020 at 11:29:42 pm EST,Crewmate,Loss,2,No,Yes,-,10m 19s,No,0.0,-,---,Europe / BNDUNF,1
37,12/09/2020 at 11:18:13 pm EST,Imposter,Win,-,-,-,5,12m 43s,No,NaN,-,+++,Europe / BNDUNF,1
38,12/09/2020 at 11:04:05 pm EST,Crewmate,Win,8,Yes,No,-,14m 01s,No,1.0,09m 28s,++,Europe / BNDUNF,1
39,12/09/2020 at 10:49:00 pm EST,Imposter,Win,-,-,-,1,15m 50s,No,NaN,-,+++,Europe / BNDUNF,1
40,12/09/2020 at 10:28:26 pm EST,Crewmate,Win,3,No,No,-,12m 58s,No,0.0,-,++,Europe / BNDUNF,1
41,12/09/2020 at 10:13:30 pm EST,Imposter,Loss,-,-,-,2,14m 59s,No,NaN,-,-,Europe / BNDUNF,1
42,12/09/2020 at 9:48:17 pm EST,Crewmate,Win,8,Yes,No,-,11m 17s,No,2.0,11m 16s,++,Europe / EUUZDF,1
43,12/09/2020 at 9:32:11 pm EST,Crewmate,Win,8,Yes,Yes,-,22m 15s,No,3.0,14m 00s,++,Europe / EUUZDF,1
44,12/09/2020 at 9:06:43 pm EST,Imposter,Loss,-,-,-,2,12m 54s,Yes,NaN,-,-,Europe / EUUZDF,1

In [7]:
crewmates_df = combined.loc[combined["Team"]== "Crewmate"]

In [8]:
imposters_df = combined.loc[combined["Team"]== "Imposter"]

In [103]:
date = combined["Game Completed Date"]

In [104]:
cleaned_date = date.str.split(expand=True)

In [105]:
cleaned_date = cleaned_date.rename(columns={0:"Date", 2: "Time", 3:"Am/Pm"})

In [106]:
cleaned_date[["Date", "Time", "Am/Pm"]]

          Date      Time Am/Pm
0   12/13/2020   1:26:56    am
1   12/13/2020   1:17:42    am
2   12/13/2020  12:57:47    am
3   12/13/2020  12:41:55    am
4   12/13/2020  12:30:37    am
..         ...       ...   ...
41  12/01/2020  11:07:41    am
42  12/01/2020  10:52:25    am
43  11/26/2020  11:23:14    am
44  11/26/2020  11:00:36    am
45  11/26/2020  10:48:50    am

[2227 rows x 3 columns]

In [107]:
cleaned_date['Time'] = pd.to_datetime(cleaned_date['Time'])

In [108]:
cleaned_date['Time'] = cleaned_date.Time.dt.hour

In [118]:
AM = cleaned_date.loc[cleaned_date["Am/Pm"]=="am"]
AM

          Date   1  Time Am/Pm    4
0   12/13/2020  at     1    am  EST
1   12/13/2020  at     1    am  EST
2   12/13/2020  at    12    am  EST
3   12/13/2020  at    12    am  EST
4   12/13/2020  at    12    am  EST
..         ...  ..   ...   ...  ...
41  12/01/2020  at    11    am  EST
42  12/01/2020  at    10    am  EST
43  11/26/2020  at    11    am  EST
44  11/26/2020  at    11    am  EST
45  11/26/2020  at    10    am  EST

[484 rows x 5 columns]

In [121]:
PM = cleaned_date.loc[cleaned_date["Am/Pm"]=="pm"]
PM["Time"] = PM["Time"] + 12
PM

<ipython-input-121-e7d0d26daea0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PM["Time"] = PM["Time"] + 12

          Date   1  Time Am/Pm    4
7   12/11/2020  at    16    pm  EST
8   12/11/2020  at    15    pm  EST
9   12/11/2020  at    15    pm  EST
10  12/11/2020  at    15    pm  EST
11  12/11/2020  at    14    pm  EST
..         ...  ..   ...   ...  ...
35  12/01/2020  at    13    pm  EST
36  12/01/2020  at    13    pm  EST
37  12/01/2020  at    24    pm  EST
38  12/01/2020  at    24    pm  EST
39  12/01/2020  at    24    pm  EST

[1743 rows x 5 columns]

In [122]:
PM_Time = PM["Time"]

In [125]:
military_time = pd.concat([AM, PM])
military_time

          Date   1  Time Am/Pm    4
0   12/13/2020  at     1    am  EST
1   12/13/2020  at     1    am  EST
2   12/13/2020  at    12    am  EST
3   12/13/2020  at    12    am  EST
4   12/13/2020  at    12    am  EST
..         ...  ..   ...   ...  ...
35  12/01/2020  at    13    pm  EST
36  12/01/2020  at    13    pm  EST
37  12/01/2020  at    24    pm  EST
38  12/01/2020  at    24    pm  EST
39  12/01/2020  at    24    pm  EST

[2227 rows x 5 columns]

In [126]:
NewTime= military_time[["Date", "Time", "Am/Pm"]]
NewTime.head

<bound method NDFrame.head of           Date  Time Am/Pm
0   12/13/2020     1    am
1   12/13/2020     1    am
2   12/13/2020    12    am
3   12/13/2020    12    am
4   12/13/2020    12    am
..         ...   ...   ...
35  12/01/2020    13    pm
36  12/01/2020    13    pm
37  12/01/2020    24    pm
38  12/01/2020    24    pm
39  12/01/2020    24    pm

[2227 rows x 3 columns]>

In [127]:
bins = [0,6,12,18,24]

# Create the names for the five bins
group_names = ["Night", "Morning", "Afternoon", "Evening"]

In [128]:
NewTime["Time of Day"] = pd.cut(NewTime["Time"], bins, labels=group_names, include_lowest=True)
NewTime

<ipython-input-128-eafa6bf80fc5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NewTime["Time of Day"] = pd.cut(NewTime["Time"], bins, labels=group_names, include_lowest=True)

          Date  Time Am/Pm Time of Day
0   12/13/2020     1    am       Night
1   12/13/2020     1    am       Night
2   12/13/2020    12    am     Morning
3   12/13/2020    12    am     Morning
4   12/13/2020    12    am     Morning
..         ...   ...   ...         ...
35  12/01/2020    13    pm   Afternoon
36  12/01/2020    13    pm   Afternoon
37  12/01/2020    24    pm     Evening
38  12/01/2020    24    pm     Evening
39  12/01/2020    24    pm     Evening

[2227 rows x 4 columns]